server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: src/main/java/com/mcm/EmployeeManagementSystem/keystore/keystore.p12
    key-store-password: marko123

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employees-management_db
    username: postgres
    password: marko
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    database: POSTGRESQL
    show-sql: true
